[package]
name = "http-params"
version = "0.1.0"
description = "HTTP request parameter access library"
authors = ["Mike Dilger <mike@optcomp.nz>"]
license = "MIT OR Apache-2.0"
keywords = ["http", "query", "parameter"]

[dependencies]
hyper = "0.11"
url = "1.5"
